language: php

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env:
        - DEPENDENCIES="--prefer-lowest"
    - php: 7.2
      env:
        - DEPENDENCIES=""
    - php: 7.3
      env:
        - DEPENDENCIES="--prefer-lowest"
    - php: 7.3
      env:
        - DEPENDENCIES=""
    - php: 7.4
      env:
        - DEPENDENCIES="--prefer-lowest"
    - php: 7.4
      env:
        - DEPENDENCIES=""
        - EXECUTE_CS_CHECK=true
        - TEST_COVERAGE=true

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

before_script:
  - composer self-update
  - composer update --prefer-source $DEPENDENCIES
  - mkdir -p tests/build/logs

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then php -dzend_extension=xdebug.so ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml --configuration ./phpunit.xml.dist; else ./vendor/bin/phpunit --configuration ./phpunit.xml.dist; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/phpcs; fi

after_success:
  - if [[ $TEST_COVERAGE == 'true' ]]; then php vendor/bin/php-coveralls -v; fi
